name: Docker Image CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Run the Docker container
      run: docker run -d -p 4000:4000 --name my-node-server my-image-name:$(date +%s)

    - name: Check if server is running
      run: |
        sleep 5
        curl --fail http://localhost:4000 || (docker logs my-node-server && exit 1)
