name: Build and Run Docker Container

on:
  push:

jobs:
  build-and-run:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: docker build -t imagename:tagname .

      - name: Run Docker container
        run: docker run -d -p 4000:4000 --name containername imagename:tagname

      - name: Check if server is running
        run: |
          sleep 5
          curl --fail http://localhost:4000 || (docker logs containername && exit 1)
